version: '3'
services:
  entekhab-salary:
    image: salarycalc
    build:
      context: .
    container_name: overtime-policies
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - ASPNETCORE_URLS=http://+:5000/
    restart: unless-stopped